- action: applied
  cloudflare_target: k8s-htz-fsn1-1.wvservices.com
  cloudflare_zone_id: 8feef835b73c3701d5ed1dd236a39102
  ingress_domain: inigma-prod.wvservices.com
  project_env: prod
  project_name: inigma
  service_name: web
- action: applied
  cloudflare_target: k8s-htz-fsn1-1.wvservices.com
  cloudflare_zone_id: 8feef835b73c3701d5ed1dd236a39102
  ingress_domain: inigma-back.wvservices.com
  project_env: prod
  project_name: inigma
  service_name: back
