- action: applied
  project_env: prod
  project_name: inigma
  service_name: web
  ingress: true
  ingress_domain: inigma-prod.wvservices.com
  cloudflare_target: k8s-htz-fsn1-1.wvservices.com
- action: applied
  project_env: prod
  project_name: inigma
  service_name: back
  ingress: false
  ingress_domain: nodomain
  cloudflare_target: nodomain
- action: destory
  project_env: prod
  project_name: inigma
  service_name: db
  ingress: false
  ingress_domain: nodomain
  cloudflare_target: nodomain
